version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/app.db
  tests:
    build: .
    volumes:
      - .:/app
    command: pytest
    environment:
      - FLASK_ENV=testing
      - DATABASE_URL=sqlite:////app/test.db